apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.4.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: client
  name: client
spec:
  ports:
  - name: "9999"
    port: 9999
    targetPort: 9999
  selector:
    io.kompose.service: client
  type: LoadBalancer
status:
  loadBalancer: {}
