version: '3'

services:

  db:
    image: postgres:9.4.4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
    volumes:
      - ../cache/postgres-data:/var/lib/postgresql/data
    labels:
      kompose.service.type: nodeport

  server:
    image: us.gcr.io/crypto-trends/server:latest
    command: bundle exec rails s -p 80 -b '0.0.0.0'
    environment:
      - DEV_SECRET_KEY_BASE='dev_secret_base'
      - DEV_SECRET_KEY_API='dev_secret_api'
      - SECRET_KEY_BASE
      - SECRET_KEY_API
    ports:
      - "9999:80"
    depends_on:
      - db
    labels:
      kompose.service.type: LoadBalancer

  client:
    image: us.gcr.io/crypto-trends/client:latest
    command: npm run start
    ports:
      - "3000:80"
    depends_on:
      - server
    labels:
      kompose.service.type: LoadBalancer
