FROM node:carbon

MAINTAINER Bob Chen <jtcdbob@gmail.com>

RUN apt-get update

ENV APP_PATH /blockterm

COPY ./client/package.json $APP_PATH/client/

WORKDIR $APP_PATH/client

RUN npm install

COPY . $APP_PATH
