version: '3'

services:

  db:
    image: postgres:9.4.4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
    volumes:
      - ../cache/postgres-data:/var/lib/postgresql/data

  server:
    image: us.gcr.io/block-191602/server:latest
    command: bundle exec rails s -p 80 -b '0.0.0.0'
    environment:
      - RAILS_ENV=development
      - SECRET_KEY_BASE=dev_secret_key_base
      - SECRET_KEY_API=dev_secret_key_api
    volumes:
      - ../server:/blockterm/
    working_dir: /blockterm/
    ports:
      - "9999:80"
    depends_on:
      - db

  client:
    image: us.gcr.io/block-191602/client:latest
    command: npm run start
    volumes:
      - ../client:/client-dev
    working_dir: /client-dev
    ports:
      - "3000:80"
    depends_on:
      - server

  cors:
    image: us.gcr.io/block-191602/cors:latest
    command: node server.js
    ports:
      - "9876:8080"
