version: '3'

services:

  db:
    image: postgres:9.4.4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
    volumes:
      - ../cache/postgres-data:/var/lib/postgresql/data
    labels:
      kompose.service.type: nodeport

  server:
    image: us.gcr.io/crypto-trends/server:latest
    command: bundle exec rails s -p 8080 -b '0.0.0.0'
    ports:
      - "9999:9999"
    depends_on:
      - db
    labels:
      kompose.service.type: LoadBalancer

  client:
    image: us.gcr.io/crypto-trends/client:latest
    command: npm start
    ports:
      - "9999:9999"
    depends_on:
      - server
    labels:
      kompose.service.type: LoadBalancer
