FROM ruby:2.3-slim

MAINTAINER Bob Chen <jtcdbob@gmail.com>

RUN apt-get update && apt-get install -qq -y \
	build-essential \
	nodejs \
	libpq-dev \
	postgresql-client-9.4 \
	--fix-missing --no-install-recommends

COPY ./server/Gemfile Gemfile

RUN bundle install

ENV APP_PATH /crypto-trends

COPY . $APP_PATH

WORKDIR $APP_PATH/server
