# For obvious reasons this file should not contain any real data
# Consider this as a template to create your secrets and you can use the information in your deployments afterwards

apiVersion: v1
kind: Secret
metadata:
  name: server
type: Opaque
data:
  base:
  api:
