export const PROJECT_VERSION = '0.2.0.1';
export const PATCH_NOTES = [
  '0.2.0.1: Added more Twitter widgets for coins such as: DRGN, KNC, RPX, and many more. Subtle changes to subreddits/tokens page, portfolio widget.',
  '0.2: Stable release of portfolio and twitter feed widgets, and volume/price delta grid. Track your total portfolio value in a few clicks!',
  '0.1.6.5: Soft launching the heavily requested "Portfolio" tab and dashboard widget, overhauling of "Coins/Tokens" page to "Price/Volume" of top 200 cryptos; [...]',
];
//<li className={css(styles.blockli)}>0.1.6.2: All Binance coins/currencies now supported via Candle Chart.</li>
//<li className={css(styles.blockli)}>Locking and unlocking of widgets now supported.</li>
//<li className={css(styles.blockli)}>[...]</li>

const DELIMETER = '__';

export const PORTFOLIO_ITEM = 'PORTFOLIO_ITEM';
export const SUBREDDIT_COMMENT_COUNTS = 'SUBREDDIT_COMMENT_COUNTS';
export const SUBREDDIT_POST_COUNTS = 'SUBREDDIT_POST_COUNTS';
export const TOTAL_MARKET_CAP = 'TOTAL_MARKET_CAP';
export const TV_CANDLE_CHART = 'TV_CANDLE_CHART';
export const TV_MARKET_OVERVIEW = 'TV_MARKET_OVERVIEW';
export const TWITTER_ITEM = 'TWITTER_ITEM';

export const ITEM_KEY_WHITELIST = [
  PORTFOLIO_ITEM,
  SUBREDDIT_COMMENT_COUNTS,
  SUBREDDIT_POST_COUNTS,
  TOTAL_MARKET_CAP,
  TV_CANDLE_CHART,
  TV_MARKET_OVERVIEW,
  TWITTER_ITEM,
];

// Array of dashboard page objects.
export const DEFAULT_PAGES_OBJECTS = [
  {
    dashboardItems:[
      {"id":"3","w":7,"h":4,"x":0,"y":0,"static":false,"identifier":"TV_CANDLE_CHART__BITSTAMP:BTCUSD"},
      {"id":"6","w":7,"h":4,"x":0,"y":4,"static":false,"identifier":"TV_CANDLE_CHART__BITSTAMP:ETHUSD"},
      {"id":"9","w":2,"h":6,"x":7,"y":6,"static":false,"identifier":"TWITTER_ITEM__#XRP, #ripple, @ripple, $XRP"},
      {"id":"10","w":4,"h":4,"x":0,"y":8,"static":false,"identifier":"TOTAL_MARKET_CAP__Default"},
      {"id":"11","w":2,"h":6,"x":7,"y":0,"static":false,"identifier":"TWITTER_ITEM__#ethereum, #ETH, $ETH"},
      {"id":"12","w":3,"h":4,"x":4,"y":8,"static":false,"identifier":"PORTFOLIO_ITEM__Default"}
    ],
    index: 0,
    name: 'Tab 1',
  },
  {
    dashboardItems: [
    ],
    index: 1,
    name: 'Tab 2',
  },
  {
    dashboardItems: [
    ],
    index: 2,
    name: 'Tab 3',
  },
  {
    dashboardItems: [
    ],
    index: 3,
    name: 'Tab 4',
  },
];

// Keys should be all lowercase.
export const DEFAULT_ITEM_OBJECTS_BY_SUBREDDIT = {
  monero: [
    {
      id: '1',
      identifier: generateIdentifier(TV_CANDLE_CHART, 'KRAKEN:XMRUSD'),
      w: 4,
      h: 4,
      x: 0,
      y: 0,
    },
    {
      id: '2',
      identifier: generateIdentifier(SUBREDDIT_POST_COUNTS, 'Monero'),
      w: 4,
      h: 4,
      x: 4,
      y: 0,
    },
    {
      id: '3',
      identifier: generateIdentifier(TV_CANDLE_CHART, 'BITTREX:XMRBTC'),
      w: 4,
      h: 4,
      x: 0,
      y: 4,
    },
    {
      id: '4',
      identifier: generateIdentifier(SUBREDDIT_COMMENT_COUNTS, 'Monero'),
      w: 4,
      h: 4,
      x: 4,
      y: 4,
    },
  ],
};

// These array values should be in user-facing order.
// The order does affect user-facing order.
export const ITEM_KEY_TO_LABELS = {
  [TV_CANDLE_CHART]: 'Candle chart',
  [TV_MARKET_OVERVIEW]: 'Market overview',
  [TOTAL_MARKET_CAP]: 'Total market cap chart',
  [PORTFOLIO_ITEM]: 'Portfolio overview',
  [SUBREDDIT_POST_COUNTS]: 'Subreddit posts chart',
  [SUBREDDIT_COMMENT_COUNTS]: 'Subreddit comments chart',
  [TWITTER_ITEM]: 'Twitter feed',
};

// These array values should be in user-facing order.
// The order does affect user-facing order.
const SUBREDDITS_IN_USER_FACING_ORDER = [
  'Bitcoin',
  'ethereum',
  'litecoin',
  'btc',
  'Ripple',
  'Iota',
  'NEO',
  'Lisk',
  'altcoin',
  'CryptoCurrency',
  'CryptoMarkets',
  'Monero',
  'Bitcoincash',
  'steemit',
  'SubstratumNetwork',
  'dogecoin',
  'Raiblocks',
  'RequestNetwork',
  'Vertcoin',
  'Electroneum',
  'Groestlcoin',
  'gridcoin',
  'icon',
  'Stellar',
  'binance',
  'helloicon',
  'enigmacatalyst',
  'BNBtrader',
];

// This map should be alphabetical for ease of development.
// The order does not affect user-facing order.
export const ITEM_VALUE_TO_LABELS = {
  'altcoin': 'r/Altcoin',
  'binance': 'r/binance',
  'Bitcoin': 'r/Bitcoin',
  'Bitcoincash': 'r/Bitcoincash',
  'BNBtrader': 'r/BNBtrader',
  'btc': 'r/BTC',
  'CryptoCurrency': 'r/Cryptocurrency',
  'CryptoMarkets': 'r/Cryptomarkets',
  'dogecoin': 'r/Dogecoin',
  'Electroneum': 'r/Electroneum',
  'enigmacatalyst': 'r/enigmacatalyst',
  'ethereum': 'r/Ethereum',
  'gridcoin': 'r/gridcoin',
  'Groestlcoin': 'r/Groestlcoin',
  'helloicon': 'r/helloicon',
  'icon': 'r/icon',
  'Iota': 'r/Iota',
  'litecoin': 'r/Litecoin',
  'Lisk': 'r/Lisk',
  'Monero': 'r/Monero',
  'NEO': 'r/NEO',
  'Raiblocks': 'r/Raiblocks',
  'RequestNetwork': 'r/RequestNetwork',
  'Ripple': 'r/Ripple',
  'steemit': 'r/steemit',
  'Stellar': 'r/Stellar',
  'SubstratumNetwork': 'r/Substratumnetwork',
  'Vertcoin': 'r/Vertcoin',
};

const TWITTER_VALUE_LIST_EXCHANGES = 'Exchanges';
const TWITTER_VALUE_SEARCH_BITCOIN = '$BTC, #Bitcoin, #BTC';
const TWITTER_VALUE_SEARCH_ETH = '#ethereum, #ETH, $ETH';
const TWITTER_VALUE_SEARCH_XRP = '#XRP, #ripple, @ripple, $XRP';
const TWITTER_VALUE_SEARCH_BCH = '#bitcoincash, #bcash, $BCH';
const TWITTER_VALUE_SEARCH_LTC = '#litecoin, $LTC, @satoshilite';
const TWITTER_VALUE_SEARCH_XEM = '$XEM, #XEM, @NEMofficial';
const TWITTER_VALUE_SEARCH_XLM = '$XLM, #XLM, #stellar, @StellarOrg';
const TWITTER_VALUE_SEARCH_IOTA = '#IOTA, #miota, $IOTA';
const TWITTER_VALUE_SEARCH_DASH = '#dashcoin, $DASH, @Dashpay';
const TWITTER_VALUE_SEARCH_NEO = '$NEO, #NEO, @NEO_Blockchain';
const TWITTER_VALUE_SEARCH_TRX = '#TRON, $TRX, @Tronfoundation, @justinsuntron';
const TWITTER_VALUE_SEARCH_EOS = '$EOS, #EOS, @EOS_io';
const TWITTER_VALUE_SEARCH_XMR = '#XMR, $XMR, #monero, @monerocurrency';
const TWITTER_VALUE_SEARCH_ICX = '$ICX, #ICX, @helloiconworld';
const TWITTER_VALUE_SEARCH_QTUM = '#QTUM, $QTUM, @QtumOfficial';
const TWITTER_VALUE_SEARCH_XRB = '@raiblocks, $XRB, #XRB';
const TWITTER_VALUE_SEARCH_ETC = '#ETC, $ETC, @eth_classic';
const TWITTER_VALUE_SEARCH_LSK = '$LSK, #LSK, @LiskHQ';
const TWITTER_VALUE_SEARCH_OMG = '$OMG, #omisego, @omise_go';
const TWITTER_VALUE_SEARCH_BNB = '$BNB, #BNB, #binancecoin, @binance_2017';
const TWITTER_VALUE_SEARCH_XVG = '#XVG, $XVG, @vergecurrency, #vergecoin';
const TWITTER_VALUE_SEARCH_ZEC = '$ZEC, #ZEC, #zcash, @zcashco';
const TWITTER_VALUE_SEARCH_VEN = '@vechainofficial, #VEN';
const TWITTER_VALUE_SEARCH_BCN = '@Bytecoin_BCN, #BCN, $BCN';
const TWITTER_VALUE_SEARCH_USDT = '@Tether_to, $USDT';
const TWITTER_VALUE_SEARCH_DOGE = '@dogecoin, #dogecoin';
const TWITTER_VALUE_SEARCH_REQ = '#RequestNetwork, $REQ, @RequestNetwork';
const TWITTER_VALUE_SEARCH_SUB = '$SUB, #substratum, @substratumnet';
const TWITTER_VALUE_SEARCH_WTC = '@waltonchain, #wtc';
const TWITTER_VALUE_SEARCH_COSS = '$COSS, #COSS, @cosscrypto';
const TWITTER_VALUE_SEARCH_RPX = '$RPX, #RPX, @red_pulse_china';
const TWITTER_VALUE_SEARCH_ARDR = '$ARDR, #ARDR, @ArdorPlatform';
const TWITTER_VALUE_SEARCH_BNTY = '$BNTY, #BNTY, @bounty0x';
const TWITTER_VALUE_SEARCH_ENJ = '$ENJ, #ENJ, @enjin';
const TWITTER_VALUE_SEARCH_PRL = '$PRL, #PRL, @OysterProtocol';
const TWITTER_VALUE_SEARCH_SNOV = '$SNOV, #SNOV, @snovio_ico';
const TWITTER_VALUE_SEARCH_DBC = '$DBC, #DBC, @DeepBrainChain';
const TWITTER_VALUE_SEARCH_DNT = '$DNT, #DNT, @district0x';
const TWITTER_VALUE_SEARCH_POE = '$POE, #POE, @_poetproject';
const TWITTER_VALUE_SEARCH_LRC = '$LRC, #LRC, @loopringorg';
const TWITTER_VALUE_SEARCH_DIVX = '$DIVX, #DIVX, @DiviProject';
const TWITTER_VALUE_SEARCH_DRGN = '$DRGN, #DRGN, @dragonchaingang';

export const TWITTER_VALUE_TO_DATA_SOURCE = {
  [TWITTER_VALUE_LIST_EXCHANGES]: {
    type: 'url',
    url: 'https://twitter.com/snowycrypto/lists/blockterm-exchanges',
  },
  [TWITTER_VALUE_SEARCH_BITCOIN]: '948031797803151362',
  [TWITTER_VALUE_SEARCH_ETH] : '951616418553913344',
  [TWITTER_VALUE_SEARCH_XRP] : '951617005659959297',
  [TWITTER_VALUE_SEARCH_BCH] : '951617488604708864',
  [TWITTER_VALUE_SEARCH_LTC] : '951612135167074304',
  [TWITTER_VALUE_SEARCH_XEM] : '951619031924002816',
  [TWITTER_VALUE_SEARCH_XLM] : '951619502776631296',
  [TWITTER_VALUE_SEARCH_IOTA] : '951620960041381888',
  [TWITTER_VALUE_SEARCH_DASH] : '951623181399240704',
  [TWITTER_VALUE_SEARCH_NEO] : '951627677722529792',
  [TWITTER_VALUE_SEARCH_TRX] : '951627018109566976',
  [TWITTER_VALUE_SEARCH_EOS] : '951628010158829568',
  [TWITTER_VALUE_SEARCH_XMR] : '951628984046862336',
  [TWITTER_VALUE_SEARCH_ICX] : '951629729475411968',
  [TWITTER_VALUE_SEARCH_QTUM] : '951629460935094274',
  [TWITTER_VALUE_SEARCH_XRB] : '951630097328435200',
  [TWITTER_VALUE_SEARCH_ETC] : '951634699838881792',
  [TWITTER_VALUE_SEARCH_LSK] : '951635074612576256',
  [TWITTER_VALUE_SEARCH_OMG] : '951635455019122688',
  [TWITTER_VALUE_SEARCH_BNB] : '951635994326982657',
  [TWITTER_VALUE_SEARCH_XVG] : '951635721995010048',
  [TWITTER_VALUE_SEARCH_ZEC] : '951636239672688640',
  [TWITTER_VALUE_SEARCH_VEN] : '951638287151546368',
  [TWITTER_VALUE_SEARCH_BCN] : '951638572632719360',
  [TWITTER_VALUE_SEARCH_USDT] : '951639305780281344',
  [TWITTER_VALUE_SEARCH_DOGE] : '951640238782205952',
  [TWITTER_VALUE_SEARCH_REQ] : '951640518798204929',
  [TWITTER_VALUE_SEARCH_SUB] : '948018703613882368',
  [TWITTER_VALUE_SEARCH_WTC] : '952980950442373120',
  [TWITTER_VALUE_SEARCH_COSS] : '953016469725503489',
  [TWITTER_VALUE_SEARCH_RPX ] : '953016215542185984',
  [TWITTER_VALUE_SEARCH_ARDR] : '953016930939518976',
  [TWITTER_VALUE_SEARCH_BNTY] : '953017165870845952',
  [TWITTER_VALUE_SEARCH_ENJ ] : '953017380879220736',
  [TWITTER_VALUE_SEARCH_PRL ] : '953017571808178177',
  [TWITTER_VALUE_SEARCH_SNOV] : '953017772677541889',
  [TWITTER_VALUE_SEARCH_DBC ] : '953017934284177408',
  [TWITTER_VALUE_SEARCH_DNT ] : '953018179218956288',
  [TWITTER_VALUE_SEARCH_POE ] : '953018360987467776',
  [TWITTER_VALUE_SEARCH_LRC ] : '953018550993612800',
  [TWITTER_VALUE_SEARCH_DIVX] : '953019780411244544',
  [TWITTER_VALUE_SEARCH_DRGN] : '953019936170917888',
};

export const ITEM_KEY_TO_VALUES = {
  [PORTFOLIO_ITEM]: [
    'Default',
  ],
  [SUBREDDIT_COMMENT_COUNTS]: SUBREDDITS_IN_USER_FACING_ORDER,
  [SUBREDDIT_POST_COUNTS]: SUBREDDITS_IN_USER_FACING_ORDER,
  [TOTAL_MARKET_CAP]: [
    'Default',
  ],
  [TV_CANDLE_CHART]: [
    'BINANCE:ADABTC',
    'BINANCE:ADAETH',
    'BINANCE:ADXBNB',
    'BINANCE:ADXBTC',
    'BINANCE:ADXETH',
    'BINANCE:AIONBNB',
    'BINANCE:AIONBTC',
    'BINANCE:AIONETH',
    'BINANCE:AMBBNB',
    'BINANCE:AMBBTC',
    'BINANCE:AMBETH',
    'BINANCE:ARKBTC',
    'BINANCE:ARKETH',
    'BINANCE:ARNBTC',
    'BINANCE:ARNETH',
    'BINANCE:ASTBTC',
    'BINANCE:ASTETH',
    'BINANCE:BATBNB',
    'BINANCE:BATBTC',
    'BINANCE:BATETH',
    'BINANCE:BCDBTC',
    'BINANCE:BCDETH',
    'BINANCE:BCPTBNB',
    'BINANCE:BCPTBTC',
    'BINANCE:BCPTETH',
    'BINANCE:BNBBTC',
    'BINANCE:BNBETH',
    'BINANCE:BNBUSDT',
    'BINANCE:BNTBTC',
    'BINANCE:BNTETH',
    'BINANCE:BQXBTC',
    'BINANCE:BQXETH',
    'BINANCE:BRDBNB',
    'BINANCE:BRDBTC',
    'BINANCE:BRDETH',
    'BINANCE:BTGBTC',
    'BINANCE:BTGETH',
    'BINANCE:BTSBNB',
    'BINANCE:BTSBTC',
    'BINANCE:BTSETH',
    'BINANCE:CDTBTC',
    'BINANCE:CDTETH',
    'BINANCE:CMTBNB',
    'BINANCE:CMTBTC',
    'BINANCE:CMTETH',
    'BINANCE:CNDBNB',
    'BINANCE:CNDBTC',
    'BINANCE:CNDETH',
    'BINANCE:CTRBTC',
    'BINANCE:CTRETH',
    'BINANCE:DGDBTC',
    'BINANCE:DGDETH',
    'BINANCE:DLTBNB',
    'BINANCE:DLTBTC',
    'BINANCE:DLTETH',
    'BINANCE:DNTBTC',
    'BINANCE:DNTETH',
    'BINANCE:EDOBTC',
    'BINANCE:EDOETH',
    'BINANCE:ELFBTC',
    'BINANCE:ELFETH',
    'BINANCE:ENGBTC',
    'BINANCE:ENGETH',
    'BINANCE:ENJBTC',
    'BINANCE:ENJETH',
    'BINANCE:EOSBTC',
    'BINANCE:ETCBTC',
    'BINANCE:EVXBTC',
    'BINANCE:EVXETH',
    'BINANCE:FUELBTC',
    'BINANCE:FUELETH',
    'BINANCE:FUNBTC',
    'BINANCE:GASBTC',
    'BINANCE:GTOBNB',
    'BINANCE:GTOBTC',
    'BINANCE:GTOETH',
    'BINANCE:GVTBTC',
    'BINANCE:GVTETH',
    'BINANCE:GXSBTC',
    'BINANCE:GXSETH',
    'BINANCE:HSRBTC',
    'BINANCE:HSRETH',
    'BINANCE:ICNBTC',
    'BINANCE:ICXBNB',
    'BINANCE:ICXBTC',
    'BINANCE:ICXETH',
    'BINANCE:IOTABNB',
    'BINANCE:IOTABTC',
    'BINANCE:IOTAETH',
    'BINANCE:KMDBTC',
    'BINANCE:KMDETH',
    'BINANCE:KNCBTC',
    'BINANCE:KNCETH',
    'BINANCE:LENDBTC',
    'BINANCE:LENDETH',
    'BINANCE:LINKBTC',
    'BINANCE:LINKETH',
    'BINANCE:LRCBTC',
    'BINANCE:LRCETH',
    'BINANCE:LSKBNB',
    'BINANCE:LSKBTC',
    'BINANCE:LSKETH',
    'BINANCE:LTCBNB',
    'BINANCE:LTCETH',
    'BINANCE:LUNBTC',
    'BINANCE:LUNETH',
    'BINANCE:MANABTC',
    'BINANCE:MANAETH',
    'BINANCE:MCOBNB',
    'BINANCE:MCOBTC',
    'BINANCE:MCOETH',
    'BINANCE:MDABTC',
    'BINANCE:MDAETH',
    'BINANCE:MODBTC',
    'BINANCE:MODETH',
    'BINANCE:MTHBTC',
    'BINANCE:MTHETH',
    'BINANCE:MTLBTC',
    'BINANCE:MTLETH',
    'BINANCE:NAVBNB',
    'BINANCE:NAVBTC',
    'BINANCE:NAVETH',
    'BINANCE:NEBLBNB',
    'BINANCE:NEBLBTC',
    'BINANCE:NEBLETH',
    'BINANCE:NEOBTC',
    'BINANCE:NULSBNB',
    'BINANCE:NULSBTC',
    'BINANCE:NULSETH',
    'BINANCE:OAXBTC',
    'BINANCE:OAXETH',
    'BINANCE:OMGBTC',
    'BINANCE:OMGETH',
    'BINANCE:OSTBNB',
    'BINANCE:OSTBTC',
    'BINANCE:OSTETH',
    'BINANCE:POEBTC',
    'BINANCE:POEETH',
    'BINANCE:POWRBNB',
    'BINANCE:POWRBTC',
    'BINANCE:POWRETH',
    'BINANCE:PPTBTC',
    'BINANCE:PPTETH',
    'BINANCE:QSPBNB',
    'BINANCE:QSPBTC',
    'BINANCE:QSPETH',
    'BINANCE:QTUMBTC',
    'BINANCE:QTUMETH',
    'BINANCE:RCNBNB',
    'BINANCE:RCNBTC',
    'BINANCE:RCNETH',
    'BINANCE:RDNBNB',
    'BINANCE:RDNBTC',
    'BINANCE:RDNETH',
    'BINANCE:REQBTC',
    'BINANCE:REQETH',
    'BINANCE:SALTBTC',
    'BINANCE:SALTETH',
    'BINANCE:SNGLSBTC',
    'BINANCE:SNGLSETH',
    'BINANCE:SNMBTC',
    'BINANCE:SNMETH',
    'BINANCE:SNTBTC',
    'BINANCE:SNTETH',
    'BINANCE:STORJBTC',
    'BINANCE:STORJETH',
    'BINANCE:STRATBTC',
    'BINANCE:SUBBTC',
    'BINANCE:SUBETH',
    'BINANCE:TNBBTC',
    'BINANCE:TNBETH',
    'BINANCE:TNTBTC',
    'BINANCE:TNTETH',
    'BINANCE:TRIGBNB',
    'BINANCE:TRIGBTC',
    'BINANCE:TRIGETH',
    'BINANCE:TRXBTC',
    'BINANCE:TRXETH',
    'BINANCE:VENBNB',
    'BINANCE:VENBTC',
    'BINANCE:VENETH',
    'BINANCE:VIBBTC',
    'BINANCE:VIBETH',
    'BINANCE:WABIBNB',
    'BINANCE:WABIBTC',
    'BINANCE:WABIETH',
    'BINANCE:WAVESBTC',
    'BINANCE:WAVESETH',
    'BINANCE:WINGSBTC',
    'BINANCE:WINGSETH',
    'BINANCE:WTCBNB',
    'BINANCE:WTCBTC',
    'BINANCE:WTCETH',
    'BINANCE:XLMBNB',
    'BINANCE:XLMBTC',
    'BINANCE:XLMETH',
    'BINANCE:XMRBTC',
    'BINANCE:XMRETH',
    'BINANCE:XRPBTC',
    'BINANCE:XVGBTC',
    'BINANCE:XVGETH',
    'BINANCE:XZCBNB',
    'BINANCE:XZCBTC',
    'BINANCE:XZCETH',
    'BINANCE:YOYOBNB',
    'BINANCE:YOYOBTC',
    'BINANCE:ZECBTC',
    'BINANCE:ZRXBTC',
    'BINANCE:ZRXETH',
    'BITFINEX:BCHBTC',
    'BITFINEX:BCHETH',
    'BITFINEX:BTCEUR',
    'BITFINEX:BTCUSD',
    'BITFINEX:BTGUSD',
    'BITFINEX:EDOBTC',
    'BITFINEX:EDOUSD',
    'BITFINEX:EOSBTC',
    'BITFINEX:EOSETH',
    'BITFINEX:EOSUSD',
    'BITFINEX:ETHUSD',
    'BITFINEX:GNTBTC',
    'BITFINEX:GNTETH',
    'BITFINEX:GNTUSD',
    'BITFINEX:IOTBTC',
    'BITFINEX:IOTETH',
    'BITFINEX:IOTEUR',
    'BITFINEX:IOTUSD',
    'BITFINEX:LTCUSD',
    'BITFINEX:NEOBTC',
    'BITFINEX:OMGUSD',
    'BITFINEX:QSHUSD',
    'BITFINEX:QSHBTC',
    'BITFINEX:QSHETH',
    'BITFINEX:QTMUSD',
    'BITFINEX:SNTBTC',
    'BITFINEX:SNTETH',
    'BITFINEX:SNTUSD',
    'BITFINEX:XMRBTC',
    'BITFINEX:XMRUSD',
    'BITFINEX:YYWBTC',
    'BITFINEX:YYWUSD',
    'BITFINEX:ZECBTC',
    'BITFINEX:ZECUSD',
    'BITFLYER:BTCJPY',
    'BITMEX:BCHXBT',
    'BITSO:BTCMXN',
    'BITSO:ETHMXN',
    'BITSO:XRPMXN',
    'BITSTAMP:BCHBTC',
    'BITSTAMP:BCHUSD',
    'BITSTAMP:BTCEUR',
    'BITSTAMP:BTCUSD',
    'BITSTAMP:ETHBTC',
    'BITSTAMP:ETHEUR',
    'BITSTAMP:ETHUSD',
    'BITSTAMP:LTCBTC',
    'BITSTAMP:LTCUSD',
    'BITSTAMP:XRPBTC',
    'BITSTAMP:XRPUSD',
    'BITTREX:1STBTC',
    'BITTREX:1STETH',
    'BITTREX:1STUSD',
    'BITTREX:ADABTC',
    'BITTREX:ADAETH',
    'BITTREX:ADAUSDT',
    'BITTREX:ADTBTC',
    'BITTREX:ADTETH',
    'BITTREX:ADTUSD',
    'BITTREX:ADXBTC',
    'BITTREX:ADXETH',
    'BITTREX:ADXUSD',
    'BITTREX:AEONBTC',
    'BITTREX:AEONUSD',
    'BITTREX:AMPBTC',
    'BITTREX:AMPUSD',
    'BITTREX:ARDRBTC',
    'BITTREX:ARDRUSD',
    'BITTREX:ARKBTC',
    'BITTREX:ARKUSD',
    'BITTREX:BATBTC',
    'BITTREX:BATUSD',
    'BITTREX:BAYBTC',
    'BITTREX:BLKBTC',
    'BITTREX:BLKUSD',
    'BITTREX:BNTBTC',
    'BITTREX:BNTETH',
    'BITTREX:BNTUSD',
    'BITTREX:BTGBTC',
    'BITTREX:BTGUSDT',
    'BITTREX:BTSUSD',
    'BITTREX:BURSTBTC',
    'BITTREX:BURSTUSD',
    'BITTREX:CANNBTC',
    'BITTREX:CANNUSD',
    'BITTREX:CFIBTC',
    'BITTREX:CFIETH',
    'BITTREX:CFIUSD',
    'BITTREX:CLOAKBTC',
    'BITTREX:CLOAKUSD',
    'BITTREX:CVCBTC',
    'BITTREX:CVCETH',
    'BITTREX:CVCUSD',
    'BITTREX:DASHBTC',
    'BITTREX:DASHETH',
    'BITTREX:DCRBTC',
    'BITTREX:DCRUSD',
    'BITTREX:DGBBTC',
    'BITTREX:DGBETH',
    'BITTREX:DGBUSD',
    'BITTREX:DGDBTC',
    'BITTREX:DGDUSD',
    'BITTREX:DMDBTC',
    'BITTREX:DMDUSD',
    'BITTREX:DNTBTC',
    'BITTREX:DOGEBTC',
    'BITTREX:DOGEUSD',
    'BITTREX:EDGBTC',
    'BITTREX:EMC2BTC',
    'BITTREX:EMC2USD',
    'BITTREX:ENGBTC',
    'BITTREX:ENGETH',
    'BITTREX:ETHUSDT',
    'BITTREX:FCTBTC',
    'BITTREX:FCTETH',
    'BITTREX:FCTUSD',
    'BITTREX:FUNBTC',
    'BITTREX:FUNUSD',
    'BITTREX:GAMEBTC',
    'BITTREX:GAMEUSD',
    'BITTREX:GCRBTC',
    'BITTREX:GCRUSD',
    'BITTREX:GNTBTC',
    'BITTREX:GNTETH',
    'BITTREX:GNTUSD',
    'BITTREX:GRCBTC',
    'BITTREX:GRCUSD',
    'BITTREX:GUPBTC',
    'BITTREX:GUPETH',
    'BITTREX:GUPUSD',
    'BITTREX:HMQBTC',
    'BITTREX:HMQETH',
    'BITTREX:HMQUSD',
    'BITTREX:IOPBTC',
    'BITTREX:IOPUSD',
    'BITTREX:KMDBTC',
    'BITTREX:KMDUSD',
    'BITTREX:LBCBTC',
    'BITTREX:LBCUSD',
    'BITTREX:LSKBTC',
    'BITTREX:LSKUSD',
    'BITTREX:LUNBTC',
    'BITTREX:LUNETH',
    'BITTREX:LUNUSD',
    'BITTREX:MAIDBTC',
    'BITTREX:MAIDUSD',
    'BITTREX:MCOBTC',
    'BITTREX:MCOETH',
    'BITTREX:MCOUSD',
    'BITTREX:MEMEBTC',
    'BITTREX:MEMEUSD',
    'BITTREX:MERBTC',
    'BITTREX:MONABTC',
    'BITTREX:MONAUSD',
    'BITTREX:NAVBTC',
    'BITTREX:NBTBTC',
    'BITTREX:NBTUSD',
    'BITTREX:NEOBTC',
    'BITTREX:NEOUSD',
    'BITTREX:NMRBTC',
    'BITTREX:NMRETH',
    'BITTREX:NMRUSD',
    'BITTREX:NXTBTC',
    'BITTREX:NXTUSD',
    'BITTREX:OKBTC',
    'BITTREX:OKUSD',
    'BITTREX:OMGBTC',
    'BITTREX:OMGUSD',
    'BITTREX:PAYBTC',
    'BITTREX:PAYETH',
    'BITTREX:PAYUSD',
    'BITTREX:PIVXBTC',
    'BITTREX:PIVXUSD',
    'BITTREX:POWRBTC',
    'BITTREX:PTOYBTC',
    'BITTREX:PTOYETH',
    'BITTREX:PTOYUSD',
    'BITTREX:QTUMBTC',
    'BITTREX:QTUMETH',
    'BITTREX:QTUMUSD',
    'BITTREX:RCNBTC',
    'BITTREX:RCNETH',
    'BITTREX:RDDBTC',
    'BITTREX:RDDUSD',
    'BITTREX:REPBTC',
    'BITTREX:REPETH',
    'BITTREX:REPUSD',
    'BITTREX:RISEBTC',
    'BITTREX:RISEUSD',
    'BITTREX:RLCBTC',
    'BITTREX:RLCETH',
    'BITTREX:RLCUSD',
    'BITTREX:SALTBTC',
    'BITTREX:SALTETH',
    'BITTREX:SBDBTC',
    'BITTREX:SBDUSD',
    'BITTREX:SCBTC',
    'BITTREX:SCETH',
    'BITTREX:SCUSD',
    'BITTREX:SLSBTC',
    'BITTREX:SLSUSD',
    'BITTREX:SNGLSUSD',
    'BITTREX:SNTBTC',
    'BITTREX:SNTETH',
    'BITTREX:SNTUSD',
    'BITTREX:SPRBTC',
    'BITTREX:SPRUSD',
    'BITTREX:STEEMBTC',
    'BITTREX:STEEMUSD',
    'BITTREX:STORJBTC',
    'BITTREX:STRATBTC',
    'BITTREX:STRATUSD',
    'BITTREX:SYSBTC',
    'BITTREX:SYSUSD',
    'BITTREX:THCBTC',
    'BITTREX:THCUSD',
    'BITTREX:TRIGBTC',
    'BITTREX:TRIGUSD',
    'BITTREX:TRSTBTC',
    'BITTREX:TRSTETH',
    'BITTREX:TRSTUSD',
    'BITTREX:TRUSTBTC',
    'BITTREX:TRUSTUSD',
    'BITTREX:UBQBTC',
    'BITTREX:UBQUSD',
    'BITTREX:UKGBTC',
    'BITTREX:UKGETH',
    'BITTREX:VIBBTC',
    'BITTREX:VIBETH',
    'BITTREX:VOXBTC',
    'BITTREX:VOXUSD',
    'BITTREX:VRCBTC',
    'BITTREX:VRCUSD',
    'BITTREX:VRMBTC',
    'BITTREX:VRMUSD',
    'BITTREX:VTCBTC',
    'BITTREX:WAVESBTC',
    'BITTREX:WAVESUSD',
    'BITTREX:WINGSBTC',
    'BITTREX:WINGSUSD',
    'BITTREX:XELBTC',
    'BITTREX:XELUSD',
    'BITTREX:XEMBTC',
    'BITTREX:XEMUSD',
    'BITTREX:XLMBTC',
    'BITTREX:XLMETH',
    'BITTREX:XLMUSD',
    'BITTREX:XMRBTC',
    'BITTREX:XMRUSD',
    'BITTREX:XVGBTC',
    'BITTREX:XVGUSD',
    'BITTREX:XZCBTC',
    'BITTREX:XZCUSD',
    'BITTREX:ZCLBTC',
    'BITTREX:ZCLUSD',
    'BITTREX:ZECBTC',
    'BITTREX:ZECUSD',
    'BITTREX:ZENBTC',
    'BITTREX:ZENUSD',
    'BTCE:DSHRUR',
    'BTCE:USDRUR',
    'BXTH:BTCTHB',
    'BXTH:ETHTHB',

    'COINBASE:BCHUSD',
    'COINBASE:BTCGBP',
    'COINBASE:BTCUSD',
    'COINBASE:ETHEUR',
    'COINBASE:ETHUSD',
    'COINBASE:LTCEUR',
    'COINBASE:LTCUSD',
    'COINFLOOR:BTCGBP',

    'HITBTC:BTCUSD',
    'HITBTC:DNTBTC',
    'HITBTC:DOGEUSD',
    'HITBTC:VERIUSD',
    'HITBTC:VERIBTC',
    'HITBTC:XEMBTC',
    'HITBTC:XEMUSD',

    'KORBIT:BCHKRW',
    'KORBIT:BTCKRW',
    'KORBIT:BTGKRW',
    'KORBIT:ETHKRW',
    'KORBIT:XRPKRW',
    'KRAKEN:BCHEUR',
    'KRAKEN:DASHEUR',
    'KRAKEN:DASHUSD',
    'KRAKEN:DASHXBT',
    'KRAKEN:EOSXBT',
    'KRAKEN:ETCEUR',
    'KRAKEN:ETCUSD',
    'KRAKEN:ETCXBT',
    'KRAKEN:ETHEUR',
    'KRAKEN:ETHJPY',
    'KRAKEN:ETHUSD',
    'KRAKEN:ETHXBT',
    'KRAKEN:ICNUSD',
    'KRAKEN:LTCEUR',
    'KRAKEN:LTCUSD',
    'KRAKEN:REPETH',
    'KRAKEN:REPEUR',
    'KRAKEN:REPXBT',
    'KRAKEN:USDTUSD',
    'KRAKEN:XMRUSD',
    'KRAKEN:XMRXBT',
    'KRAKEN:XRPEUR',
    'KRAKEN:XRPUSD',
    'KRAKEN:XRPXBT',
    'KRAKEN:ZECEUR',
    'KRAKEN:ZECXBT',
    'MERCADO:BCHBRL',
    'MERCADO:BTCBRL',
    'MERCADO:LTCBRL',


    'POLONIEX:AMPBTC',
    'POLONIEX:AMPUSD',
    'POLONIEX:ARDRBTC',
    'POLONIEX:ARDRUSD',
    'POLONIEX:BCHUSDT',
    'POLONIEX:BLKBTC',
    'POLONIEX:BLKUSD',
    'POLONIEX:BLKXMR',
    'POLONIEX:BTCDBTC',
    'POLONIEX:BTCUSDT',
    'POLONIEX:BTMBTC',
    'POLONIEX:BTSBTC',
    'POLONIEX:BTSUSD',
    'POLONIEX:BURSTBTC',
    'POLONIEX:BURSTUSD',
    'POLONIEX:CVCBTC',
    'POLONIEX:CVCETH',
    'POLONIEX:DASHBTC',
    'POLONIEX:DASHUSDT',
    'POLONIEX:DCRBTC',
    'POLONIEX:DCRUSD',
    'POLONIEX:DGBBTC',
    'POLONIEX:EMC2BTC',
    'POLONIEX:EMC2USD',
    'POLONIEX:ETHBTC',
    'POLONIEX:ETHUSDT',
    'POLONIEX:FCTBTC',
    'POLONIEX:FCTUSD',
    'POLONIEX:GAMEBTC',
    'POLONIEX:GAMEUSD',
    'POLONIEX:GASBTC',
    'POLONIEX:GASETH',
    'POLONIEX:GNTBTC',
    'POLONIEX:GNTETH',
    'POLONIEX:GNTUSD',
    'POLONIEX:GRCBTC',
    'POLONIEX:LBCBTC',
    'POLONIEX:LBCUSD',
    'POLONIEX:LSKBTC',
    'POLONIEX:MAIDBTC',
    'POLONIEX:MAIDUSD',
    'POLONIEX:NAVBTC',
    'POLONIEX:NXTBTC',
    'POLONIEX:NXTUSD',
    'POLONIEX:NXTUSDT',
    'POLONIEX:OMGBTC',
    'POLONIEX:OMGETH',
    'POLONIEX:REPBTC',
    'POLONIEX:REPETH',
    'POLONIEX:REPUSD',
    'POLONIEX:REPUSDT',
    'POLONIEX:SBDBTC',
    'POLONIEX:SCBTC',
    'POLONIEX:SCUSD',
    'POLONIEX:STRBTC',
    'POLONIEX:STEEMBTC',
    'POLONIEX:STEEMETH',
    'POLONIEX:STORJBTC',
    'POLONIEX:STRATBTC',
    'POLONIEX:STRATUSD',
    'POLONIEX:SYSBTC',
    'POLONIEX:SYSUSD',
    'POLONIEX:USDTBTC',
    'POLONIEX:USDTUSD',
    'POLONIEX:VRCBTC',
    'POLONIEX:VRCUSD',
    'POLONIEX:VTCBTC',
    'POLONIEX:XEMBTC',
    'POLONIEX:XMRUSDT',
    'POLONIEX:XPMBTC',
    'POLONIEX:XPMUSD',
    'POLONIEX:XRPBTC',
    'POLONIEX:XRPUSDT',
    'POLONIEX:ZRXBTC',
    'POLONIEX:ZRXETH',
    'POLONIEX:ZRXUSD',


    'THEROCKTRADING:BTCXRP',
    'WEX:BCHRUR',
    'WEX:DSHEUR',
    'WEX:ETHRUR',
    'WEX:LTCRUR',
    'WEX:USDRUR',
  ],
  [TV_MARKET_OVERVIEW]: [
    'Default',
  ],
  [TWITTER_ITEM]: [
    TWITTER_VALUE_LIST_EXCHANGES,
    TWITTER_VALUE_SEARCH_BITCOIN,
    TWITTER_VALUE_SEARCH_ETH,
    TWITTER_VALUE_SEARCH_XRP,
    TWITTER_VALUE_SEARCH_BCH,
    TWITTER_VALUE_SEARCH_LTC,
    TWITTER_VALUE_SEARCH_XEM,
    TWITTER_VALUE_SEARCH_XLM,
    TWITTER_VALUE_SEARCH_IOTA,
    TWITTER_VALUE_SEARCH_DASH,
    TWITTER_VALUE_SEARCH_NEO,
    TWITTER_VALUE_SEARCH_TRX,
    TWITTER_VALUE_SEARCH_EOS,
    TWITTER_VALUE_SEARCH_XMR,
    TWITTER_VALUE_SEARCH_ICX,
    TWITTER_VALUE_SEARCH_QTUM,
    TWITTER_VALUE_SEARCH_XRB,
    TWITTER_VALUE_SEARCH_ETC,
    TWITTER_VALUE_SEARCH_LSK,
    TWITTER_VALUE_SEARCH_OMG,
    TWITTER_VALUE_SEARCH_BNB,
    TWITTER_VALUE_SEARCH_XVG,
    TWITTER_VALUE_SEARCH_ZEC,
    TWITTER_VALUE_SEARCH_VEN,
    TWITTER_VALUE_SEARCH_BCN,
    TWITTER_VALUE_SEARCH_USDT,
    TWITTER_VALUE_SEARCH_DOGE,
    TWITTER_VALUE_SEARCH_REQ,
    TWITTER_VALUE_SEARCH_SUB,
    TWITTER_VALUE_SEARCH_WTC,
    TWITTER_VALUE_SEARCH_COSS,
    TWITTER_VALUE_SEARCH_RPX,
    TWITTER_VALUE_SEARCH_ARDR,
    TWITTER_VALUE_SEARCH_BNTY,
    TWITTER_VALUE_SEARCH_ENJ,
    TWITTER_VALUE_SEARCH_PRL,
    TWITTER_VALUE_SEARCH_SNOV,
    TWITTER_VALUE_SEARCH_DBC,
    TWITTER_VALUE_SEARCH_DNT,
    TWITTER_VALUE_SEARCH_POE,
    TWITTER_VALUE_SEARCH_LRC,
    TWITTER_VALUE_SEARCH_DIVX,
    TWITTER_VALUE_SEARCH_DRGN,
    TWITTER_VALUE_SEARCH_XVG,
  ],
};

// const TWITTER_
export const ITEM_VALUE_TO_IMAGE = {
    'BINANCE:ADABTC': 'cardano',
    'BINANCE:ADAETH': 'cardano',
    'BINANCE:ADXBNB': 'cardano',
    'BINANCE:ADXBTC': 'cardano',
    'BINANCE:ADXETH': 'cardano',
    'BINANCE:AIONBNB': 'aion',
    'BINANCE:AIONBTC': 'aion',
    'BINANCE:AIONETH': 'aion',
    'BINANCE:AMBBNB': 'amber',
    'BINANCE:AMBBTC': 'amber',
    'BINANCE:AMBETH': 'amber',
    'BINANCE:ARKBTC': 'ark',
    'BINANCE:ARKETH': 'ark',
    'BINANCE:ARNBTC': 'aeron',
    'BINANCE:ARNETH': 'aeron',
    'BINANCE:ASTBTC': 'airswap',
    'BINANCE:ASTETH': 'airswap',
    'BINANCE:BATBNB': 'basic-attention-token',
    'BINANCE:BATBTC': 'basic-attention-token',
    'BINANCE:BATETH': 'basic-attention-token',
    'BINANCE:BCDBTC':'bitcoin-diamond',
    'BINANCE:BCDETH':'bitcoin-diamond',
    'BINANCE:BCPTBNB':'blockmason',
    'BINANCE:BCPTBTC':'blockmason',
    'BINANCE:BCPTETH':'blockmason',
    'BINANCE:BNBBTC': 'binance-coin',
    'BINANCE:BNBETH': 'binance-coin',
    'BINANCE:BNBUSDT': 'binance-coin',
    'BINANCE:BNTBTC':'bancor',
    'BINANCE:BNTETH':'bancor',
    'BINANCE:BRDBNB': 'bread',
    'BINANCE:BRDBTC': 'bread',
    'BINANCE:BRDETH': 'bread',
    'BINANCE:BTGBTC': 'bitcoin-gold',
    'BINANCE:BTGETH': 'bitcoin-gold',
    'BINANCE:BTSBNB': 'bitshares',
    'BINANCE:BTSBTC': 'bitshares',
    'BINANCE:BTSETH': 'bitshares',
    'BINANCE:CDTBTC': 'coindash',
    'BINANCE:CDTETH': 'coindash',
    'BINANCE:CMTBNB': 'cybermiles',
    'BINANCE:CMTBTC': 'cybermiles',
    'BINANCE:CMTETH': 'cybermiles',
    'BINANCE:CNDBNB': 'cindicator',
    'BINANCE:CNDBTC': 'cindicator',
    'BINANCE:CNDETH': 'cindicator',
    'BINANCE:CTRBTC': 'centra',
    'BINANCE:CTRETH': 'centra',
    'BINANCE:DGDBTC': 'digixdao',
    'BINANCE:DGDETH': 'digixdao',
    'BINANCE:DLTBNB': 'agrello-delta',
    'BINANCE:DLTBTC': 'agrello-delta',
    'BINANCE:DLTETH': 'agrello-delta',
    'BINANCE:DNTBTC': 'district0x',
    'BINANCE:DNTETH': 'district0x',
    'BINANCE:EDOBTC': 'eidoo',
    'BINANCE:EDOETH': 'eidoo',
    'BINANCE:ELFBTC': 'aelf',
    'BINANCE:ELFETH': 'aelf',
    'BINANCE:ENGBTC': 'enigma-project',
    'BINANCE:ENGETH': 'enigma-project',
    'BINANCE:ENJBTC': 'enjin-coin',
    'BINANCE:ENJETH': 'enjin-coin',
    'BINANCE:EOSBTC': 'eos',
    'BINANCE:ETCBTC': 'ethereum-classic',
    'BINANCE:EVXBTC': 'everex',
    'BINANCE:EVXETH': 'everex',
    'BINANCE:FUELBTC': 'etherparty',
    'BINANCE:FUELETH': 'etherparty',
    'BINANCE:FUNBTC': 'funfair',
    'BINANCE:GASBTC': 'gas',
    'BINANCE:GTOBNB': 'gifto',
    'BINANCE:GTOBTC': 'gifto',
    'BINANCE:GTOETH': 'gifto',
    'BINANCE:GVTBTC': 'genesis-vision',
    'BINANCE:GVTETH': 'genesis-vision',
    'BINANCE:GXSBTC': 'gxshares',
    'BINANCE:GXSETH': 'gxshares',
    'BINANCE:HSRBTC': 'hshare',
    'BINANCE:HSRETH': 'hshare',
    'BINANCE:ICNBTC': 'iconomi',
    'BINANCE:ICXBNB': 'icon',
    'BINANCE:ICXBTC': 'icon',
    'BINANCE:ICXETH': 'icon',
    'BINANCE:IOTABNB': 'iota',
    'BINANCE:IOTABTC': 'iota',
    'BINANCE:IOTAETH': 'iota',
    'BINANCE:KMDBTC': 'komodo',
    'BINANCE:KMDETH': 'komodo',
    'BINANCE:KNCBTC': 'kyber-network',
    'BINANCE:KNCETH': 'kyber-network',
    'BINANCE:LENDBTC': 'ethlend',
    'BINANCE:LENDETH': 'ethlend',
    'BINANCE:LINKBTC': 'chainlink',
    'BINANCE:LINKETH': 'chainlink',
    'BINANCE:LRCBTC': 'loopring',
    'BINANCE:LRCETH': 'loopring',
    'BINANCE:LSKBNB': 'lisk',
    'BINANCE:LSKBTC': 'lisk',
    'BINANCE:LSKETH': 'lisk',
    'BINANCE:LTCBNB': 'litecoin',
    'BINANCE:LTCETH': 'litecoin',
    'BINANCE:LUNBTC': 'lunyr',
    'BINANCE:LUNETH': 'lunyr',
    'BINANCE:MANABTC': 'decentraland',
    'BINANCE:MANAETH': 'decentraland',
    'BINANCE:MCOBNB': 'monaco',
    'BINANCE:MCOBTC': 'monaco',
    'BINANCE:MCOETH': 'monaco',
    'BINANCE:MDABTC': 'moeda-loyalty-points',
    'BINANCE:MDAETH': 'moeda-loyalty-points',
    'BINANCE:MODBTC': 'modum',
    'BINANCE:MODETH': 'modum',
    'BINANCE:MTHBTC': 'monetha',
    'BINANCE:MTHETH': 'monetha',
    'BINANCE:MTLBTC': 'metal',
    'BINANCE:MTLETH': 'metal',
    'BINANCE:NAVBNB': 'nav-coin',
    'BINANCE:NAVBTC': 'nav-coin',
    'BINANCE:NAVETH': 'nav-coin',
    'BINANCE:NEBLBNB': 'neblio',
    'BINANCE:NEBLBTC': 'neblio',
    'BINANCE:NEOBTC': 'neo',
    'BINANCE:NULSBNB': 'nuls',
    'BINANCE:NULSBTC': 'nuls',
    'BINANCE:NULSETH': 'nuls',
    'BINANCE:OAXBTC': 'oax',
    'BINANCE:OAXETH': 'oax',
    'BINANCE:OMGBTC': 'omisego',
    'BINANCE:OMGETH': 'omisego',
    'BINANCE:OSTBNB': 'simple-token',
    'BINANCE:OSTBTC': 'simple-token',
    'BINANCE:OSTETH': 'simple-token',
    'BINANCE:POEBTC': 'poet',
    'BINANCE:POEETH': 'poet',
    'BINANCE:POWRBNB': 'power-ledger',
    'BINANCE:POWRBTC': 'power-ledger',
    'BINANCE:POWRETH': 'power-ledger',
    'BINANCE:PPTBTC': 'populous',
    'BINANCE:PPTETH': 'populous',
    'BINANCE:QSPBNB': 'quantstamp',
    'BINANCE:QSPBTC': 'quantstamp',
    'BINANCE:QSPETH': 'quantstamp',
    'BINANCE:QTUMBTC': 'qtum',
    'BINANCE:QTUMETH': 'qtum',
    'BINANCE:RCNBNB': 'ripio-credit-network',
    'BINANCE:RCNBTC': 'ripio-credit-network',
    'BINANCE:RCNETH': 'ripio-credit-network',
    'BINANCE:RDNBNB':'raiden-network-token',
    'BINANCE:RDNBTC':'raiden-network-token',
    'BINANCE:RDNETH':'raiden-network-token',
    'BINANCE:REQBTC': 'request-network',
    'BINANCE:REQETH': 'request-network',
    'BINANCE:SALTBTC': 'salt',
    'BINANCE:SALTETH': 'salt',
    'BINANCE:SNGLSBTC': 'singulardtv',
    'BINANCE:SNGLSETH': 'singulardtv',
    'BINANCE:SNMBTC': 'sonm',
    'BINANCE:SNMETH': 'sonm',
    'BINANCE:SNTBTC': 'status',
    'BINANCE:SNTETH': 'status',
    'BINANCE:STORJBTC': 'storj',
    'BINANCE:STORJETH': 'storj',
    'BINANCE:STRATBTC': 'stratis',
    'BINANCE:SUBBTC': 'substratum',
    'BINANCE:SUBETH': 'substratum',
    'BINANCE:TNBBTC': 'time-new-bank',
    'BINANCE:TNBETH': 'time-new-bank',
    'BINANCE:TNTBTC': 'tierion',
    'BINANCE:TNTETH': 'tierion',
    'BINANCE:TRIGBNB': 'triggers',
    'BINANCE:TRIGBTC': 'triggers',
    'BINANCE:TRIGETH': 'triggers',
    'BINANCE:TRXBTC': 'tron',
    'BINANCE:TRXETH': 'tron',
    'BINANCE:VENBNB': 'vechain',
    'BINANCE:VENBTC': 'vechain',
    'BINANCE:VENETH': 'vechain',
    'BINANCE:VIBBTC': 'viberate',
    'BINANCE:VIBETH': 'viberate',
    'BINANCE:WABIBNB': 'wabi',
    'BINANCE:WABIBTC': 'wabi',
    'BINANCE:WABIETH': 'wabi',
    'BINANCE:WAVESBTC': 'waves',
    'BINANCE:WAVESETH': 'waves',
    'BINANCE:WINGSBTC': 'wings',
    'BINANCE:WINGSETH': 'wings',
    'BINANCE:WTCBNB': 'walton',
    'BINANCE:WTCBTC': 'walton',
    'BINANCE:WTCETH': 'walton',
    'BINANCE:XLMBNB': 'stellar',
    'BINANCE:XLMBTC': 'stellar',
    'BINANCE:XLMETH': 'stellar',
    'BINANCE:XMRBTC': 'monero',
    'BINANCE:XMRETH': 'monero',
    'BINANCE:XRPBTC': 'ripple',
    'BINANCE:XVGBTC': 'verge',
    'BINANCE:XVGETH': 'verge',
    'BINANCE:XZCBNB': 'zcoin',
    'BINANCE:XZCBTC': 'zcoin',
    'BINANCE:XZCETH': 'zcoin',
    'BINANCE:YOYOBNB': 'yoyow',
    'BINANCE:YOYOBTC': 'yoyow',
    'BINANCE:ZECBTC': 'zcash',
    'BINANCE:ZRXBTC': '0x',
    'BINANCE:ZRXETH': '0x',
    'BITFINEX:BCHBTC': 'bitcoin-cash',
    'BITFINEX:BCHETH': 'bitcoin-cash',
    'BITFINEX:BTCEUR': 'bitcoin',
    'BITFINEX:BTCUSD': 'bitcoin',
    'BITFINEX:BTGUSD': 'bitcoin-gold',
    'BITFINEX:EDOBTC': 'eidoo',
    'BITFINEX:EDOUSD': 'eidoo',
    'BITFINEX:EOSBTC': 'eos',
    'BITFINEX:EOSETH': 'eos',
    'BITFINEX:EOSUSD': 'eos',
    'BITFINEX:ETHUSD': 'ethereum',
    'BITFINEX:GNTBTC': 'golem-network-tokens',
    'BITFINEX:GNTETH': 'golem-network-tokens',
    'BITFINEX:GNTUSD': 'golem-network-tokens',
    'BITFINEX:IOTBTC': 'iota',
    'BITFINEX:IOTETH': 'iota',
    'BITFINEX:IOTEUR': 'iota',
    'BITFINEX:IOTUSD': 'iota',
    'BITFINEX:LTCUSD': 'litecoin',
    'BITFINEX:NEOBTC': 'neo',
    'BITFINEX:QSHUSD': 'qash',
    'BITFINEX:OMGUSD': 'omisego',
    'BITFINEX:QTMUSD': 'qtum',
    'BITFINEX:SNTBTC': 'status',
    'BITFINEX:SNTETH': 'status',
    'BITFINEX:SNTUSD': 'status',
    'BITFINEX:XMRBTC': 'monero',
    'BITFINEX:XMRUSD': 'monero',
    'BITFINEX:YYWBTC': 'yoyow',
    'BITFINEX:YYWUSD': 'yoyow',
    'BITFINEX:ZECBTC': 'zcash',
    'BITFINEX:ZECUSD': 'zcash',
    'BITFLYER:BTCJPY': 'bitcoin',
    'BITMEX:BCHXBT': 'bitcoin-cash',
    'BITSO:BTCMXN': 'bitcoin',
    'BITSO:ETHMXN': 'ethereum',
    'BITSO:XRPMXN': 'ripple',
    'BITSTAMP:BCHBTC': 'bitcoin-cash',
    'BITSTAMP:BCHUSD': 'bitcoin-cash',
    'BITSTAMP:BTCEUR': 'bitcoin',
    'BITSTAMP:BTCUSD': 'bitcoin',
    'BITSTAMP:ETHBTC': 'ethereum',
    'BITSTAMP:ETHEUR': 'ethereum',
    'BITSTAMP:ETHUSD': 'ethereum',
    'BITSTAMP:LTCBTC': 'litecoin',
    'BITSTAMP:LTCUSD': 'litecoin',
    'BITSTAMP:XRPBTC': 'ripple',
    'BITSTAMP:XRPUSD': 'ripple',
    'BITTREX:1STBTC': 'firstblood',
    'BITTREX:1STETH': 'firstblood',
    'BITTREX:1STUSD': 'firstblood',
    'BITTREX:ADABTC': 'cardano',
    'BITTREX:ADAETH': 'cardano',
    'BITTREX:ADAUSDT': 'cardano',
    'BITTREX:ADTBTC': 'adtoken',
    'BITTREX:ADTETH': 'adtoken',
    'BITTREX:ADTUSD': 'adtoken',
    'BITTREX:ADXBTC': 'adx-net',
    'BITTREX:ADXETH': 'adx-net',
    'BITTREX:ADXUSD': 'adx-net',
    'BITTREX:AEONBTC': 'aeon',
    'BITTREX:AEONUSD': 'aeon',
    'BITTREX:AMPBTC': 'synereo',
    'BITTREX:AMPUSD': 'synereo',
    'BITTREX:ARDRBTC': 'ardor',
    'BITTREX:ARDRUSD': 'ardor',
    'BITTREX:ARKBTC': 'ark',
    'BITTREX:ARKUSD': 'ark',
    'BITTREX:BATBTC': 'basic-attention-token',
    'BITTREX:BATUSD': 'basic-attention-token',
    'BITTREX:BAYBTC': 'bitbay',
    'BITTREX:BLKBTC': 'blackcoin',
    'BITTREX:BLKUSD': 'blackcoin',
    'BITTREX:BNTBTC': 'bancor',
    'BITTREX:BNTETH': 'bancor',
    'BITTREX:BNTUSD': 'bancor',
    'BITTREX:BTGBTC': 'bitcoin-gold',
    'BITTREX:BTGUSDT': 'bitcoin-gold',
    'BITTREX:BTSUSD': 'bitshares',
    'BITTREX:BURSTBTC': 'burst',
    'BITTREX:BURSTUSD': 'burst',
    'BITTREX:CANNBTC': 'cannabiscoin',
    'BITTREX:CANNUSD': 'cannabiscoin',
    'BITTREX:CFIBTC':'cofound-it',
    'BITTREX:CFIETH':'cofound-it',
    'BITTREX:CFIUSD':'cofound-it',
    'BITTREX:CLOAKBTC': 'cloakcoin',
    'BITTREX:CLOAKUSD': 'cloakcoin',
    'BITTREX:CVCBTC': 'civic',
    'BITTREX:CVCETH': 'civic',
    'BITTREX:CVCUSD': 'civic',
    'BITTREX:DASHBTC': 'dash',
    'BITTREX:DASHETH': 'dash',
    'BITTREX:DCRBTC': 'decred',
    'BITTREX:DCRUSD': 'decred',
    'BITTREX:DGBBTC': 'digibyte',
    'BITTREX:DGBETH': 'digibyte',
    'BITTREX:DGBUSD': 'digibyte',
    'BITTREX:DGDBTC': 'digixdao',
    'BITTREX:DGDUSD': 'digixdao',
    'BITTREX:DMDBTC': 'diamond',
    'BITTREX:DMDUSD': 'diamond',
    'BITTREX:DNTBTC': 'district0x',
    'BITTREX:DOGEBTC': 'dogecoin',
    'BITTREX:DOGEUSD': 'dogecoin',
    'BITTREX:EDGBTC': 'edgeless',
    'BITTREX:EMC2BTC': 'einsteinium',
    'BITTREX:EMC2USD': 'einsteinium',
    'BITTREX:ENGBTC': 'enigma-project',
    'BITTREX:ENGETH': 'enigma-project',
    'BITTREX:ETHUSDT': 'ethereum',
    'BITTREX:FCTBTC': 'factom',
    'BITTREX:FCTETH': 'factom',
    'BITTREX:FCTUSD': 'factom',
    'BITTREX:FUNBTC': 'funfair',
    'BITTREX:FUNUSD': 'funfair',
    'BITTREX:GAMEBTC': 'gamecredits',
    'BITTREX:GAMEUSD': 'gamecredits',
    'BITTREX:GCRBTC': 'global-currency-reserve',
    'BITTREX:GCRUSD': 'global-currency-reserve',
    'BITTREX:GNTBTC': 'golem-network-tokens',
    'BITTREX:GNTETH': 'golem-network-tokens',
    'BITTREX:GNTUSD': 'golem-network-tokens',
    'BITTREX:GRCBTC': 'gridcoin',
    'BITTREX:GRCUSD': 'gridcoin',
    'BITTREX:GUPBTC':'guppy',
    'BITTREX:GUPETH':'guppy',
    'BITTREX:GUPUSD':'guppy',
    'BITTREX:HMQBTC': 'humaniq',
    'BITTREX:HMQETH': 'humaniq',
    'BITTREX:HMQUSD': 'humaniq',
    'BITTREX:IOPBTC': 'internet-of-people',
    'BITTREX:IOPUSD': 'internet-of-people',
    'BITTREX:KMDBTC': 'komodo',
    'BITTREX:KMDUSD': 'komodo',
    'BITTREX:LBCBTC': 'library-credit',
    'BITTREX:LBCUSD': 'library-credit',
    'BITTREX:LSKBTC': 'lisk',
    'BITTREX:LSKUSD': 'lisk',
    'BITTREX:LUNBTC': 'lunyr',
    'BITTREX:LUNETH': 'lunyr',
    'BITTREX:LUNUSD': 'lunyr',
    'BITTREX:MAIDBTC': 'maidsafecoin',
    'BITTREX:MAIDUSD': 'maidsafecoin',
    'BITTREX:MCOBTC': 'monaco',
    'BITTREX:MCOETH': 'monaco',
    'BITTREX:MCOUSD': 'monaco',
    'BITTREX:MEMEBTC': 'memetic',
    'BITTREX:MEMEUSD': 'memetic',
    'BITTREX:MERBTC': 'mercury',
    'BITTREX:MONABTC': 'monacoin',
    'BITTREX:MONAUSD': 'monacoin',
    'BITTREX:NAVBTC': 'nav-coin',
    'BITTREX:NBTBTC': 'nubits',
    'BITTREX:NBTUSD': 'nubits',
    'BITTREX:NEOBTC': 'neo',
    'BITTREX:NEOUSD': 'neo',
    'BITTREX:NMRBTC': 'numeraire',
    'BITTREX:NMRETH': 'numeraire',
    'BITTREX:NMRUSD': 'numeraire',
    'BITTREX:NXTBTC': 'nxt',
    'BITTREX:NXTUSD': 'nxt',
    'BITTREX:OKBTC': 'okcash',
    'BITTREX:OKUSD': 'okcash',
    'BITTREX:OMGBTC': 'omisego',
    'BITTREX:OMGUSD': 'omisego',
    'BITTREX:PAYBTC': 'tenx',
    'BITTREX:PAYETH': 'tenx',
    'BITTREX:PAYUSD': 'tenx',
    'BITTREX:PIVXBTC': 'pivx',
    'BITTREX:PIVXUSD': 'pivx',
    'BITTREX:POWRBTC': 'power-ledger',
    'BITTREX:PTOYBTC': 'patientory',
    'BITTREX:PTOYETH': 'patientory',
    'BITTREX:PTOYUSD': 'patientory',
    'BITTREX:QTUMBTC': 'qtum',
    'BITTREX:QTUMETH': 'qtum',
    'BITTREX:QTUMUSD': 'qtum',
    'BITTREX:RCNBTC': 'ripio-credit-network',
    'BITTREX:RCNETH': 'ripio-credit-network',
    'BITTREX:RDDBTC': 'reddcoin',
    'BITTREX:RDDUSD': 'reddcoin',
    'BITTREX:REPBTC': 'augur',
    'BITTREX:REPETH': 'augur',
    'BITTREX:REPUSD': 'augur',
    'BITTREX:RISEBTC': 'rise',
    'BITTREX:RISEUSD': 'rise',
    'BITTREX:RLCBTC': 'rlc',
    'BITTREX:RLCETH': 'rlc',
    'BITTREX:RLCUSD': 'rlc',
    'BITTREX:SALTBTC': 'salt',
    'BITTREX:SALTETH': 'salt',
    'BITTREX:SBDBTC': 'steem-dollars',
    'BITTREX:SBDUSD': 'steem-dollars',
    'BITTREX:SCBTC': 'siacoin',
    'BITTREX:SCETH': 'siacoin',
    'BITTREX:SCUSD': 'siacoin',
    'BITTREX:SLSBTC': 'salus',
    'BITTREX:SLSUSD': 'salus',
    'BITTREX:SNGLSUSD': 'singulardtv',
    'BITTREX:SNTBTC': 'status',
    'BITTREX:SNTETH': 'status',
    'BITTREX:SNTUSD': 'status',
    'BITTREX:SPRBTC': 'spreadcoin',
    'BITTREX:SPRUSD': 'spreadcoin',
    'BITTREX:STEEMBTC': 'steem',
    'BITTREX:STEEMUSD': 'steem',
    'BITTREX:STORJBTC': 'storj',
    'BITTREX:STRATBTC': 'stratis',
    'BITTREX:STRATUSD': 'stratis',
    'BITTREX:SYSBTC': 'syscoin',
    'BITTREX:SYSUSD': 'syscoin',
    'BITTREX:THCBTC': 'hempcoin',
    'BITTREX:THCUSD': 'hempcoin',
    'BITTREX:TRIGBTC': 'triggers',
    'BITTREX:TRIGUSD': 'triggers',
    'BITTREX:TRSTBTC': 'trust',
    'BITTREX:TRSTETH': 'trust',
    'BITTREX:TRSTUSD': 'trust',
    'BITTREX:TRUSTBTC': 'trustplus',
    'BITTREX:TRUSTUSD': 'trustplus',
    'BITTREX:UBQBTC': 'ubiq',
    'BITTREX:UBQUSD': 'ubiq',
    'BITTREX:UKGBTC': 'unikoin-gold',
    'BITTREX:UKGETH': 'unikoin-gold',
    'BITTREX:VIBBTC': 'viberate',
    'BITTREX:VIBETH': 'viberate',
    'BITTREX:VOXBTC': 'voxels',
    'BITTREX:VOXUSD': 'voxels',
    'BITTREX:VTCBTC': 'vertcoin',
    'BITTREX:VRCBTC': 'vericoin',
    'BITTREX:VRCUSD': 'vericoin',
    'BITTREX:VRMBTC': 'veriumreserve',
    'BITTREX:VRMUSD': 'veriumreserve',
    'BITTREX:WAVESBTC': 'waves',
    'BITTREX:WAVESUSD': 'waves',
    'BITTREX:WINGSBTC': 'wings',
    'BITTREX:WINGSUSD': 'wings',
    'BITTREX:XELBTC': 'elastic',
    'BITTREX:XELUSD': 'elastic',
    'BITTREX:XEMBTC': 'nem',
    'BITTREX:XEMUSD': 'nem',
    'BITTREX:XLMBTC': 'stellar',
    'BITTREX:XLMETH': 'stellar',
    'BITTREX:XLMUSD': 'stellar',
    'BITTREX:XMRBTC': 'monero',
    'BITTREX:XMRUSD': 'monero',
    'BITTREX:XVGBTC': 'verge',
    'BITTREX:XVGUSD': 'verge',
    'BITTREX:XZCBTC': 'zcoin',
    'BITTREX:XZCUSD': 'zcoin',
    'BITTREX:ZCLBTC': 'zclassic',
    'BITTREX:ZCLUSD': 'zclassic',
    'BITTREX:ZECBTC': 'zcash',
    'BITTREX:ZECUSD': 'zcash',
    'BITTREX:ZENBTC': 'zencash',
    'BITTREX:ZENUSD': 'zencash',
    'BTCE:DSHRUR': 'dashcoin',
    'BXTH:BTCTHB': 'bitcoin',
    'BXTH:ETHTHB': 'ethereum',
    'COINBASE:BCHUSD': 'bitcoin-cash',
    'COINBASE:BTCGBP': 'bitcoin',
    'COINBASE:BTCUSD': 'bitcoin',
    'COINBASE:ETHEUR': 'ethereum',
    'COINBASE:ETHUSD': 'ethereum',
    'COINBASE:LTCEUR': 'litecoin',
    'COINBASE:LTCUSD': 'litecoin',
    'COINFLOOR:BTCGBP': 'bitcoin',

    'HITBTC:BTCUSD': 'bitcoin',
    'HITBTC:DNTBTC': 'district0x',
    'HITBTC:DOGEUSD': 'dogecoin',
    'HITBTC:VERIUSD': 'veritaseum',
    'HITBTC:VERIBTC': 'veritaseum',
    'HITBTC:XEMBTC': 'nem',
    'HITBTC:XEMUSD': 'nem',

    'KORBIT:BCHKRW': 'bitcoin-cash',
    'KORBIT:BTCKRW': 'bitcoin',
    'KORBIT:BTGKRW': 'bitcoin-gold',
    'KORBIT:ETHKRW': 'ethereum',
    'KORBIT:XRPKRW': 'ripple',
    'KRAKEN:BCHEUR': 'bitcoin-cash',
    'KRAKEN:DASHEUR': 'dash',
    'KRAKEN:DASHUSD': 'dash',
    'KRAKEN:DASHXBT': 'dash',
    'KRAKEN:EOSXBT': 'eos',
    'KRAKEN:ETCEUR': 'ethereum-classic',
    'KRAKEN:ETCUSD': 'ethereum-classic',
    'KRAKEN:ETCXBT': 'ethereum-classic',
    'KRAKEN:ETHEUR': 'ethereum',
    'KRAKEN:ETHJPY': 'ethereum',
    'KRAKEN:ETHUSD': 'ethereum',
    'KRAKEN:ETHXBT': 'ethereum',
    'KRAKEN:ICNUSD': 'iconomi',
    'KRAKEN:LTCEUR': 'litecoin',
    'KRAKEN:LTCUSD': 'litecoin',
    'KRAKEN:REPETH': 'augur',
    'KRAKEN:REPEUR': 'augur',
    'KRAKEN:REPXBT': 'augur',
    'KRAKEN:USDTUSD': 'tether',
    'KRAKEN:XMRUSD': 'monero',
    'KRAKEN:XMRXBT': 'monero',
    'KRAKEN:XRPEUR': 'ripple',
    'KRAKEN:XRPUSD': 'ripple',
    'KRAKEN:XRPXBT': 'ripple',
    'KRAKEN:ZECEUR': 'zcash',
    'KRAKEN:ZECXBT': 'zcash',
    'MERCADO:BCHBRL': 'bitcoin-cash',
    'MERCADO:BTCBRL': 'bitcoin',
    'MERCADO:LTCBRL': 'litecoin',
    'POLONIEX:AMPBTC': 'synereo',
    'POLONIEX:AMPUSD': 'synereo',
    'POLONIEX:ARDRBTC': 'ardor',
    'POLONIEX:ARDRUSD': 'ardor',
    'POLONIEX:BCHUSDT': 'bitcoin-cash',
    'POLONIEX:BLKBTC': 'blackcoin',
    'POLONIEX:BLKUSD': 'blackcoin',
    'POLONIEX:BLKXMR': 'blackcoin',
    'POLONIEX:BTMBTC': 'bytom',
    'POLONIEX:BTSBTC': 'bitshares',
    'POLONIEX:BTSUSD': 'bitshares',
    'POLONIEX:BURSTBTC': 'burst',
    'POLONIEX:BURSTUSD': 'burst',
    'POLONIEX:CVCBTC': 'civic',
    'POLONIEX:CVCETH': 'civic',
    'POLONIEX:DASHBTC': 'dash',
    'POLONIEX:DASHUSDT': 'dash',
    'POLONIEX:DCRBTC': 'decred',
    'POLONIEX:DCRUSD': 'decred',
    'POLONIEX:DGBBTC': 'digibyte',
    'POLONIEX:EMC2BTC': 'einsteinium',
    'POLONIEX:EMC2USD': 'einsteinium',
    'POLONIEX:FCTBTC': 'factom',
    'POLONIEX:FCTUSD': 'factom',
    'POLONIEX:GAMEBTC':'gamecredits',
    'POLONIEX:GAMEUSD':'gamecredits',
    'POLONIEX:GASBTC': 'gas',
    'POLONIEX:GASETH': 'gas',
    'POLONIEX:GNTBTC': 'golem-network-tokens',
    'POLONIEX:GNTETH': 'golem-network-tokens',
    'POLONIEX:GNTUSD': 'golem-network-tokens',
    'POLONIEX:GRCBTC': 'gridcoin',
    'POLONIEX:LBCBTC': 'library-credit',
    'POLONIEX:LBCUSD': 'library-credit',
    'POLONIEX:LSKBTC': 'lisk',
    'POLONIEX:MAIDBTC': 'maidsafecoin',
    'POLONIEX:MAIDUSD': 'maidsafecoin',
    'POLONIEX:NAVBTC': 'nav-coin',
    'POLONIEX:NXTBTC': 'nxt',
    'POLONIEX:NXTUSD': 'nxt',
    'POLONIEX:NXTUSDT': 'nxt',
    'POLONIEX:OMGBTC': 'omisego',
    'POLONIEX:OMGETH': 'omisego',
    'POLONIEX:REPBTC': 'augur',
    'POLONIEX:REPETH': 'augur',
    'POLONIEX:REPUSD': 'augur',
    'POLONIEX:REPUSDT': 'augur',
    'POLONIEX:SBDBTC': 'steem-dollars',
    'POLONIEX:SCBTC': 'siacoin',
    'POLONIEX:SCUSD': 'siacoin',
    'POLONIEX:STEEMBTC': 'steem',
    'POLONIEX:STEEMETH': 'steem',
    'POLONIEX:STORJBTC': 'storj',
    'POLONIEX:STRATBTC': 'stratis',
    'POLONIEX:SYSBTC': 'syscoin',
    'POLONIEX:SYSUSD': 'syscoin',
    'POLONIEX:USDTBTC': 'tether',
    'POLONIEX:USDTUSD': 'tether',
    'POLONIEX:VTCBTC': 'vertcoin',
    'POLONIEX:XEMBTC': 'nem',
    'POLONIEX:XPMBTC': 'primecoin',
    'POLONIEX:XPMUSD': 'primecoin',
    'POLONIEX:XRPUSDT': 'ripple',
    'POLONIEX:ZRXBTC': '0x',
    'POLONIEX:ZRXETH': '0x',
    'POLONIEX:ZRXUSD': '0x',

    'THEROCKTRADING:BTCXRP': 'bitcoin',
    'WEX:BCHRUR': 'bitcoin-cash',
    'WEX:DSHEUR': 'dashcoin',
    'WEX:ETHRUR': 'ethereum',
    'WEX:LTCRUR': 'litecoin',
};

export function getImageUrl(imageName)
{
  return imageName ?
    `https://files.coinmarketcap.com/static/img/coins/64x64/${imageName}.png` :
    null;
}

function checkConflict(x, y, w, h, dashboardItems)
{
  return dashboardItems.filter((item) => {
    if (x >= item.x + item.w || item.x >= x + w)
    {
      return false;
    }
    if (y >= item.y + item.h || item.y >= y + h)
    {
      return false;
    }
    return true;
  }).length > 0;
}

// Returns an array of [next X coordinate to use, next Y coordinate to use, next id to use].
export function computeDashboardFreeValues(dashboardItems, w, h)
{
  var maxId = 0;
  var maxY = 0;
  dashboardItems.forEach((dashboardItem) => {
    maxId = Math.max(maxId, parseInt(dashboardItem.id));
    maxY = Math.max(maxY, dashboardItem.y + dashboardItem.h);
  });

  var nextX = 0;
  var nextY = 0;
  while (nextY <= maxY + 1)
  {
    while (nextX <= 9 - w)
    {
      if (!checkConflict(nextX, nextY, w, h, dashboardItems))
      {
        return [nextX, nextY, String(maxId + 1)];
      }
      nextX += 1;
    }
    nextX = 0;
    nextY += 1;
  }

  // Fail safe return.
  return [0, maxY + 1, String(maxId + 1)];
}

export function generateIdentifier(key, value)
{
  if (!ITEM_KEY_WHITELIST.includes(key))
  {
    if (process.env.NODE_ENV === 'dev')
    {
      console.log('Invalid identifier');
    }
    return null;
  }
  else
  {
    return `${key}${DELIMETER}${value}`;
  }
}

export function isIdentifierValid(identifier)
{
  const arr = identifier.split(DELIMETER, 2);
  const identifierKey = arr[0];
  const identifierValue = arr[1];
  return ITEM_KEY_WHITELIST.includes(identifierKey);
}

export function parseIdentifer(identifier)
{
  if (!isIdentifierValid(identifier))
  {
    if (process.env.NODE_ENV === 'dev')
    {
      console.log('Invalid identifier');
    }
    return null;
  }
  else
  {
    return identifier.split(DELIMETER, 2);
  }
}

export function parseIdentiferKey(identifier)
{
  const [identifierKey, identifierValue] = parseIdentifer(identifier);
  return identifierKey ? identifierKey : null;
}

export function convertIdentifierToTitle(identifier)
{
  var [identifierKey, identifierValue] = parseIdentifer(identifier);
  if (identifierKey === TV_CANDLE_CHART)
  {
    identifierKey = 'CANDLE_CHART';
  }
  else if (identifierKey === PORTFOLIO_ITEM)
  {
    identifierKey = 'PORTFOLIO';
  }
  else if (identifierKey === TWITTER_ITEM)
  {
    identifierKey = 'TWITTER';
  }
  return `${identifierKey}:${identifierValue}`;
}
