export const PORTFOLIO_SORT_BY_BALANCE = 'PORTFOLIO_SORT_BY_BALANCE';
export const PORTFOLIO_SORT_BY_EXCHANGE = 'PORTFOLIO_SORT_BY_EXCHANGE';
export const PORTFOLIO_SORT_BY_HOLDING = 'PORTFOLIO_SORT_BY_BY_HOLDING';
export const PORTFOLIO_SORT_BY_PRICE = 'PORTFOLIO_SORT_BY_PRICE';
export const PORTFOLIO_SORT_BY_TOKEN = 'PORTFOLIO_SORT_BY_TOKEN';
