export const WORKER_MESSAGE_TYPE_ALERTS = 'WORKER_MESSAGE_TYPE_ALERTS';
export const WORKER_MESSAGE_TYPE_EXCHANGE_KEYS = 'WORKER_MESSAGE_TYPE_EXCHANGE_KEYS';
export const WORKER_MESSAGE_TYPE_TICKERS = 'WORKER_MESSAGE_TYPE_TICKERS';

export const WORKER_REPLY_TYPE_ALERT = 'WORKER_REPLY_TYPE_ALERT';
export const WORKER_REPLY_TYPE_BALANCE = 'WORKER_REPLY_TYPE_BALANCE';
export const WORKER_REPLY_TYPE_TICKER = 'WORKER_REPLY_TYPE_TICKER';
